### ISSUE TITLE
CTK I AM SHORT PANTS OR FULLSCOPE JEDI PLEASE UNBAN ME PLEASE

### ISSUE THREAD

**Issue by afthab208** [CTK-WARRIOR/Discord-Bot-Dashboard#2]

**Comment by Rishiraj0100** [comment]
Nope,
Your mistake banned you, and if there is time punishment  then you will be automatically unbanned or just go banned.
Happy Punishment!

**Comment by afthab208** [comment]
I DIDNT EVEN DO ANYTHING
